### ISSUE TITLE
DataMoment not observing data field size

### ISSUE THREAD

**Issue by phemmer** [bwiggs/go-nexrad#4]
Currently the values within a [`DataMoment`](https://godoc.org/github.com/bwiggs/go-nexrad/archive2#DataMoment) are exposed as a byte array (`DataMoment.Data`). On top of this, the [`ScaledData()`](https://godoc.org/github.com/bwiggs/go-nexrad/archive2#DataMoment.ScaledData) method iterates over this array as if it were a slice of `uint8` (`byte`).

This usage is not correct as the data type is not guaranteed to be `uint8`. Instead the `DataWordSize` must be used to determine the type. If the value is `16`, then `DataMoment.Data` needs to be unmarshalled as a vector of big endian `uint16`.

**Comment by bwiggs** [comment]
16bit fields should be working fine now. I was able to generate ZDR using some of the latest scans successfully.

![image](https://user-images.githubusercontent.com/7358/173405735-684c2f1b-453f-4ab6-8fd8-e7484552b665.png)
