### ISSUE TITLE
Data Block - unknown type ''

### ISSUE THREAD

**Issue by millisecond** [bwiggs/go-nexrad#5]
Trying to render a recent radar scan from the same site as your Harvey example i.e. https://noaa-nexrad-level2.s3.amazonaws.com/2021/09/19/KCRP/KCRP20210919_000249_V06 and getting the same failure reading both as a library and via nexrad-render CLI: 

`go run main.go -f KCRP20210919_002125_V06` 

Output: 

```
Generating ref from KCRP20210919_002125_V06 -> radar.png
PANI[0000] Data Block - unknown type ''              
panic: (*logrus.Entry) 0xc000146070

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0001467e0, 0xc0000120f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
```

Debugging in, it looks like the m31 header is correct but the DataBlock is corrupt.  Let me know if I can provide anything else.

**Comment by bwiggs** [comment]
Thanks for the report. Looks like latest `ICD FOR RDA/RPG - Build RDA 19.0/RPG 19.0 (PDF)` [found here](https://www.roc.noaa.gov/WSR88D/BuildInfo/Files.aspx) on page `3-127` has added a new moment data type. We'll need to add support for an extra moment field, and dynamic data moment pointers to handle legacy files as well as new files.

There are some good reports on other project on github that had to deal with the same issue. See https://github.com/ARM-DOE/pyart/issues/887

I'm working on a fix.

**Comment by bwiggs** [comment]
Pushed a fix for this to master

**Comment by millisecond** [comment]
Awesome, thanks so much for fixing!
